### ISSUE TITLE
FineGrain Perms ?

### ISSUE THREAD

**Issue by mrajwadk** [mgregoro/SVN-Access#1]
hi

Does this module handle FineGrain Repository permissions ?
aka PathBasedAuthz ?

http://svnbook.red-bean.com/nightly/en/svn.serverconfig.pathbasedauthz.html

**Comment by mgregoro** [comment]
It sure does, that’s what it was originally written to manage, actually.

**Comment by mgregoro** [comment]
Responded right away; closing issue.
